### ISSUE TITLE
Quotation marks in PDF

### ISSUE THREAD

**Issue by neagle** [manuelkiessling/nodebeginner.org#25]
Hi - please forgive me if this isn't the best place to post this issue. I just happily paid for the eBook version of The Node Beginner Book - the beginning was excellent and I'm continuing to enjoy the book. I've switched to the PDF version, and I'm a bit dismayed to find that all of the quotation mark pairs are &rdquo;mangled&rdquo;. (It's not incredibly obvious in this font, but all of the quotation marks are right double quotes, which looks painful in a serif font.

It looks like there are at least some apostrophe issues, too. (See page 31, where "we're" becomes "weâ€TMre".

These aren't huge issues and I don't regret buying the book, but it'd be lovely not to have these ugly typographic stains on an otherwise great product.

**Comment by manuelkiessling** [comment]
I'm afraid I can't fix this. The Markdown -> PDF conversion is done by Leanpub. I think they did improve this in the meanwhile, though - I've just copied over a code snippet from the current PDF version, and the quotation marks were correct.
