### ISSUE TITLE
Is this repos active?

### ISSUE THREAD

**Issue by NDFA** [manuelkiessling/nodebeginner.org#69]
It seems its been a while you've not been here @manuelkiessling . Isn't it?
There are some easy-to-solve issues, some solved ones(like #65 ), even two test(!) issues and no one is responsible for them.

Will you continue to develop the project or we should fork it(I myself prefer to continue on the main branch/version)?

**Comment by manuelkiessling** [comment]
Thanks for bringing this up. I will try to go through all issues and PRs.
