### ISSUE TITLE
DepreciationWarning: Calling an asynchronous function without callback is deprecated

### ISSUE THREAD

**Issue by leoreeves** [manuelkiessling/nodebeginner.org#74]
I keep getting this error with my own code as well as your version of the application which I downloaded from this repo.  Also, when I upload the image it doesn't appear in the tmp/ directory, Any ideas on how to fix?

````
(node:14700) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:14700) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
fs.js:90
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, unlink 'D:\Documents\GitHub\projects\node.js-beginner-web-app\tmp\test.png'
````

`http://localhost:8888/upload` returns this:

![error](https://cloud.githubusercontent.com/assets/15375448/22398055/5f526ba2-e577-11e6-91f9-48591adc33fa.png)

I'm using node 7.4.0 and the latest version of formidable.

**Comment by fml077** [comment]
I met this error too.
